# Generated by Django 3.1.2 on 2020-10-22 05:53

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201022_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='coordinate',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
