# Generated by Django 3.1.2 on 2020-10-22 06:05

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201022_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='coordinate',
            field=geoposition.fields.GeopositionField(max_length=42, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='remember',
            name='remember',
            field=models.TextField(verbose_name='Воспоминание'),
        ),
    ]
